color: red
description: 'For blog, news, etc'
fieldLayouts:
  5b91d4b1-2be9-4a10-b86a-1199186ef879:
    cardThumbAlignment: end
    cardView:
      - authors
      - type
      - postDate
      - 'layoutElement:ff63510c-bbb1-4d7e-b412-9c21dd6c54ce'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-27T12:27:25+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3575c544-fef2-482f-a14c-3e7cea5cb5f5
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-02-05T02:45:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 583773bb-c99b-4af2-b0d2-831f43d66009 # Excerpt
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff63510c-bbb1-4d7e-b412-9c21dd6c54ce
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-27T20:57:11+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 22aa2642-9879-40d9-aa0e-28fb6ace4584 # Body
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 960c74a7-74db-4e91-af42-fcb483a197d6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-01-27T20:58:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1e29e7d4-9352-42e0-8b25-317fdfe2f756 # Featured Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22ece500-61f6-4234-a87c-989cdd830468
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 952badf2-bc40-43a6-adeb-7036ca12b30c
        userCondition: null
handle: news
hasTitleField: true
icon: square-rss
name: News
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
