altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  0019ad61-ec31-4dfb-8b99-033b85691283:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-01-27T20:57:31+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 073fac08-b0e8-442c-8e1a-569805f6b2ef
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c0005300-8e7f-4b4a-ae32-761b000e190f
        userCondition: null
fs: local
handle: siteImages
name: 'Site Images'
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
